In [ ]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from google.colab import drive
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

In [ ]:
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
# import necessary libraries
import pandas as pd
import os
import glob

# use glob to get all the csv files
# in the folder
#no_placa = 333
#basic_path = "/content/drive/MyDrive/Datos_inventados/Placa_"+str(no_placa)+"_"

path = ["/content/drive/MyDrive/simulaciones/simulaciones/Placa_4051832242505266978_40", "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4052113717481977659_40",
        "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4195384480627701530_40", "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4195947430581122850_40",
        "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4267442074665629512_40", "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4267723549642340101_40",
        "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4269130924525893449_40", "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4340062618656978738_40",
        "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4340344085043753791_40", "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4412964637625038597_40"]

df=pd.DataFrame()
all_rows = []

for i in range(len(path)):
  csv_files = glob.glob(os.path.join(path[i], "*.csv"))
  # loop over the list of csv files
  for f in csv_files:
    
    new_row = np.transpose(pd.read_csv(f,header=None).values)
    
    if len(all_rows)==0:
      all_rows = new_row
    else:
      all_rows = np.vstack([all_rows, new_row])
all_rows
all_columns = np.transpose(all_rows)
all_columns


array([[4280755967, 4280755967, 4280755967, ..., 4280690431, 4280690431,
        4280690431],
       [         0,          0,          0, ...,          0,          0,
                 0],
       [      1488,       1488,       1488, ...,       1503,       1503,
              1503],
       ...,
       [      1489,       1489,       1489, ...,       1503,       1504,
              1503],
       [1111111111, 1111111111, 1111111111, ..., 1111111111, 1111111111,
        1111111111],
       [1111111110, 1111111110, 1111111110, ..., 1111111110, 1111111110,
        1111111110]])

In [ ]:
all_columns = pd.DataFrame(all_columns)
all_columns

0           1           2           3           4    \
0       4280755967  4280755967  4280755967  4280755967  4280755967   
1                0           0           0           0           0   
2             1488        1488        1488        1488        1488   
3              922         922         922         922         922   
4             1195        1195        1195        1195        1195   
...            ...         ...         ...         ...         ...   
159203        1490        1489        1489        1490        1490   
159204         937         938         937         938         937   
159205        1489        1489        1489        1490        1489   
159206  1111111111  1111111111  1111111111  1111111111  1111111111   
159207  1111111110  1111111110  1111111110  1111111110  1111111110   

               5           6           7           8           9    ...  \
0       4280755967  4280755967  4280755967  4280755967  4280755967  ...   
1                0           0           0           0           0  ...   
2             1488        1488        1488        1488        1488  ...   
3              922         922         922         922         922  ...   
4             1195        1195        1195        1195        1195  ...   
...            ...         ...         ...         ...         ...  ...   
159203        1489        1489        1489        1489        1490  ...   
159204         936         937         936         937         937  ...   
159205        1489        1489        1490        1489        1489  ...   
159206  1111111111  1111111111  1111111111  1111111111  1111111111  ...   
159207  1111111110  1111111110  1111111110  1111111110  1111111110  ...   

               990         991         992         993         994  \
0       4280690431  4280690431  4280690431  4280690431  4280690431   
1                0           0           0           0           0   
2             1503        1503        1503        1503        1503   
3              927         927         927         927         927   
4             1201        1201        1201        1201        1201   
...            ...         ...         ...         ...         ...   
159203        1503        1502        1502        1503        1503   
159204         940         939         939         940         939   
159205        1504        1503        1502        1503        1503   
159206  1111111111  1111111111  1111111111  1111111111  1111111111   
159207  1111111110  1111111110  1111111110  1111111110  1111111110   

               995         996         997         998         999  
0       4280690431  4280690431  4280690431  4280690431  4280690431  
1                0           0           0           0           0  
2             1503        1503        1503        1503        1503  
3              927         927         927         927         927  
4             1201        1201        1201        1201        1201  
...            ...         ...         ...         ...         ...  
159203        1503        1502        1502        1503        1503  
159204         939         939         939         940         941  
159205        1503        1502        1503        1504        1503  
159206  1111111111  1111111111  1111111111  1111111111  1111111111  
159207  1111111110  1111111110  1111111110  1111111110  1111111110  

[159208 rows x 1000 columns]

In [ ]:
all_columns2 = all_columns[6:159206]

In [ ]:
all_columns2

0     1     2     3     4     5     6     7     8     9    ...   990  \
6        938   936   937   937   937   938   938   938   937   937  ...   939   
7       1489  1488  1490  1489  1489  1489  1490  1491  1490  1489  ...  1502   
8        936   936   938   936   937   936   936   937   936   937  ...   940   
9       1489  1489  1489  1490  1490  1489  1489  1489  1490  1489  ...  1502   
10       937   938   936   938   937   937   938   937   935   937  ...   938   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
159201  1489  1489  1489  1489  1489  1490  1490  1490  1489  1490  ...  1502   
159202   936   936   937   936   936   937   937   936   936   937  ...   939   
159203  1490  1489  1489  1490  1490  1489  1489  1489  1489  1490  ...  1503   
159204   937   938   937   938   937   936   937   936   937   937  ...   940   
159205  1489  1489  1489  1490  1489  1489  1489  1490  1489  1489  ...  1504   

         991   992   993   994   995   996   997   998   999  
6        940   940   939   941   940   940   938   939   939  
7       1503  1502  1502  1502  1503  1503  1503  1502  1502  
8        940   940   939   939   940   940   938   939   939  
9       1503  1502  1503  1502  1503  1502  1502  1502  1502  
10       938   940   939   940   939   939   939   940   938  
...      ...   ...   ...   ...   ...   ...   ...   ...   ...  
159201  1503  1503  1501  1503  1503  1503  1503  1501  1503  
159202   940   939   940   939   940   939   939   940   940  
159203  1502  1502  1503  1503  1503  1502  1502  1503  1503  
159204   939   939   940   939   939   939   939   940   941  
159205  1503  1502  1503  1503  1503  1502  1503  1504  1503  

[159200 rows x 1000 columns]

In [ ]:
temp = []
for i in range(len(all_columns2)):
  if ( i % 2 == 0):
    temp = np.append(temp, all_columns2.iloc[i], axis = 0)

temp = np.reshape(temp, (79600,1000))
temp = np.transpose(temp)
print(temp)

[[938. 936. 937. ... 937. 936. 937.]
 [936. 936. 938. ... 936. 936. 938.]
 [937. 938. 936. ... 936. 937. 937.]
 ...
 [938. 938. 939. ... 939. 939. 939.]
 [939. 939. 940. ... 939. 940. 940.]
 [939. 939. 938. ... 939. 940. 941.]]


In [ ]:
volt = []
for i in range(len(all_columns2)):
  if ( i % 2 == 1):
    volt = np.append(volt, all_columns2.iloc[i], axis = 0)

volt = np.reshape(volt, (79600,1000))
volt = np.transpose(volt)
print(volt)

[[1489. 1489. 1489. ... 1489. 1490. 1489.]
 [1488. 1489. 1489. ... 1489. 1489. 1489.]
 [1490. 1489. 1489. ... 1489. 1489. 1489.]
 ...
 [1503. 1502. 1502. ... 1503. 1502. 1503.]
 [1502. 1502. 1502. ... 1501. 1503. 1504.]
 [1502. 1502. 1504. ... 1503. 1503. 1503.]]


In [ ]:
id = []
for i in range(10):
  for j in range(100):
    id.append(i+1)
id = np.reshape(id,(1000,1))

In [ ]:
alg = []
for i in range(len(temp)):
  alg.append(1)
alg = np.reshape(alg,(1000,1))
alg

In [ ]:
time = []
for i in range(len(temp)):
  time.append(i+1)
time = np.reshape(time,(1000,1))
time

In [ ]:
temp_id = np.append(id, alg, axis = 1)
temp_id = np.append(temp_id, time, axis = 1)
temp_id = np.append(temp_id, temp, axis = 1)
temp_id = pd.DataFrame(temp_id)
temp_id=temp_id.astype(int)
temp_id.rename(columns={temp_id.columns[0]:'id'}, inplace=True)
temp_id.rename(columns={temp_id.columns[1]:'alg'}, inplace=True)
temp_id.rename(columns={temp_id.columns[2]:'time'}, inplace=True)

In [ ]:
temp_id

id  alg  time    3    4    5    6    7    8    9  ...  79593  79594  \
0     1    1     1  938  936  937  937  938  937  937  ...    936    937   
1     1    1     2  936  936  938  936  937  938  937  ...    937    937   
2     1    1     3  937  938  936  936  938  937  937  ...    937    936   
3     1    1     4  937  936  938  936  937  938  937  ...    936    936   
4     1    1     5  937  937  937  937  937  937  937  ...    937    936   
..   ..  ...   ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
995  10    1   996  940  940  939  940  938  940  940  ...    940    940   
996  10    1   997  940  940  939  940  939  940  939  ...    939    941   
997  10    1   998  938  938  939  940  939  940  939  ...    939    940   
998  10    1   999  939  939  940  940  939  940  939  ...    940    938   
999  10    1  1000  939  939  938  939  941  939  939  ...    939    938   

     79595  79596  79597  79598  79599  79600  79601  79602  
0      937    935    937    936    937    937    936    937  
1      937    938    936    938    937    936    936    938  
2      937    937    937    937    936    936    937    937  
3      937    937    937    937    939    937    936    938  
4      937    936    937    936    937    937    936    937  
..     ...    ...    ...    ...    ...    ...    ...    ...  
995    941    940    939    938    938    938    940    939  
996    939    940    939    939    940    939    939    939  
997    940    938    939    940    940    939    939    939  
998    939    939    940    939    940    939    940    940  
999    939    939    939    940    939    939    940    941  

[1000 rows x 79603 columns]

In [ ]:
volt_id = np.append(id, alg, axis = 1)
volt_id = np.append (volt_id, time, axis = 1)
volt_id = np.append (volt_id, volt, axis = 1)
volt_id = pd.DataFrame(volt_id)
volt_id=volt_id.astype(int)
volt_id.rename(columns={volt_id.columns[0]:'id'}, inplace=True)
volt_id.rename(columns={volt_id.columns[1]:'alg'}, inplace=True)
volt_id.rename(columns={volt_id.columns[2]:'time'}, inplace=True)

In [ ]:
volt_id

id  alg  time     3     4     5     6     7     8     9  ...  79593  \
0     1    1     1  1489  1489  1489  1489  1489  1490  1489  ...   1490   
1     1    1     2  1488  1489  1489  1490  1489  1489  1489  ...   1490   
2     1    1     3  1490  1489  1489  1489  1489  1489  1490  ...   1489   
3     1    1     4  1489  1490  1491  1489  1489  1489  1490  ...   1490   
4     1    1     5  1489  1490  1491  1489  1489  1490  1489  ...   1490   
..   ..  ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
995  10    1   996  1503  1503  1503  1503  1502  1502  1502  ...   1503   
996  10    1   997  1503  1502  1502  1503  1503  1503  1502  ...   1502   
997  10    1   998  1503  1502  1502  1503  1502  1503  1503  ...   1503   
998  10    1   999  1502  1502  1502  1502  1502  1503  1502  ...   1501   
999  10    1  1000  1502  1502  1504  1503  1502  1503  1503  ...   1503   

     79594  79595  79596  79597  79598  79599  79600  79601  79602  
0     1490   1490   1490   1488   1489   1489   1489   1490   1489  
1     1489   1489   1490   1490   1489   1490   1489   1489   1489  
2     1489   1489   1490   1489   1489   1489   1489   1489   1489  
3     1489   1489   1489   1489   1489   1489   1489   1490   1490  
4     1490   1489   1489   1489   1489   1488   1489   1490   1489  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
995   1502   1503   1503   1503   1503   1503   1503   1503   1503  
996   1503   1502   1503   1502   1503   1503   1503   1502   1502  
997   1503   1503   1503   1502   1503   1504   1503   1502   1503  
998   1502   1503   1502   1502   1503   1504   1501   1503   1504  
999   1502   1503   1502   1503   1503   1503   1503   1503   1503  

[1000 rows x 79603 columns]

In [ ]:
print(temp_id)
temp_id.shape

     id  alg  time    3    4    5    6    7    8    9  ...  79593  79594  \
0     1    1     1  938  936  937  937  938  937  937  ...    936    937   
1     1    1     2  936  936  938  936  937  938  937  ...    937    937   
2     1    1     3  937  938  936  936  938  937  937  ...    937    936   
3     1    1     4  937  936  938  936  937  938  937  ...    936    936   
4     1    1     5  937  937  937  937  937  937  937  ...    937    936   
..   ..  ...   ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
995  10    1   996  940  940  939  940  938  940  940  ...    940    940   
996  10    1   997  940  940  939  940  939  940  939  ...    939    941   
997  10    1   998  938  938  939  940  939  940  939  ...    939    940   
998  10    1   999  939  939  940  940  939  940  939  ...    940    938   
999  10    1  1000  939  939  938  939  941  939  939  ...    939    938   

     79595  79596  79597  79598  79599  79600  79601  79602  
0      937    935    937 

(1000, 79603)

In [ ]:
print(volt_id)
volt_id.shape

     id  alg  time     3     4     5     6     7     8     9  ...  79593  \
0     1    1     1  1489  1489  1489  1489  1489  1490  1489  ...   1490   
1     1    1     2  1488  1489  1489  1490  1489  1489  1489  ...   1490   
2     1    1     3  1490  1489  1489  1489  1489  1489  1490  ...   1489   
3     1    1     4  1489  1490  1491  1489  1489  1489  1490  ...   1490   
4     1    1     5  1489  1490  1491  1489  1489  1490  1489  ...   1490   
..   ..  ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
995  10    1   996  1503  1503  1503  1503  1502  1502  1502  ...   1503   
996  10    1   997  1503  1502  1502  1503  1503  1503  1502  ...   1502   
997  10    1   998  1503  1502  1502  1503  1502  1503  1503  ...   1503   
998  10    1   999  1502  1502  1502  1502  1502  1503  1502  ...   1501   
999  10    1  1000  1502  1502  1504  1503  1502  1503  1503  ...   1503   

     79594  79595  79596  79597  79598  79599  79600  79601  79602  
0     1490   1490 

(1000, 79603)

In [ ]:
temp_id.to_csv('temp_alg1.csv')

In [ ]:
volt_id.to_csv('volt_alg1.csv')