In [ ]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from google.colab import drive
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

In [ ]:
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
import pandas as pd
 
temp_alg1 = pd.read_csv("/content/drive/MyDrive/simulaciones/simulaciones/Placa_4051832242505266978_42/datos_2.csv")
 
print(temp_alg1)

                 1
0                0
1             1488
2              922
3             1195
4                0
...            ...
200002        1490
200003         934
200004        1490
200005  1111111111
200006  1111111110

[200007 rows x 1 columns]


In [ ]:
# import necessary libraries
import pandas as pd
import os
import glob

# use glob to get all the csv files
# in the folder
#no_placa = 333
#basic_path = "/content/drive/MyDrive/Datos_inventados/Placa_"+str(no_placa)+"_"

path = ["/content/drive/MyDrive/simulaciones/simulaciones/Placa_4051832242505266978_41", "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4052113717481977659_41",
        "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4195384480627701530_41", "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4195947430581122850_41",
        "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4267442074665629512_41", "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4267723549642340101_41",
        "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4269130924525893449_41", "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4340062618656978738_41",
        "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4340344085043753791_41", "/content/drive/MyDrive/simulaciones/simulaciones/Placa_4412964637625038597_41"]

df=pd.DataFrame()
all_rows = []

for i in range(len(path)):
  csv_files = glob.glob(os.path.join(path[i], "*.csv"))
  # loop over the list of csv files
  for f in csv_files:
    
    new_row = np.transpose(pd.read_csv(f,header=None).values)
    
    if len(all_rows)==0:
      all_rows = new_row
    else:
      all_rows = np.vstack([all_rows, new_row])
all_rows
all_columns = np.transpose(all_rows)
all_columns


array([[4280755967, 4280755967, 4280755967, ..., 4280690431, 4280690431,
        4280690431],
       [         0,          0,          0, ...,          0,          0,
                 0],
       [      1488,       1488,       1488, ...,       1503,       1503,
              1503],
       ...,
       [      1490,       1489,       1489, ...,       1503,       1503,
              1503],
       [1111111111, 1111111111, 1111111111, ..., 1111111111, 1111111111,
        1111111111],
       [1111111110, 1111111110, 1111111110, ..., 1111111110, 1111111110,
        1111111110]])

In [ ]:
all_columns = pd.DataFrame(all_columns)
all_columns

0           1           2           3           4    \
0       4280755967  4280755967  4280755967  4280755967  4280755967   
1                0           0           0           0           0   
2             1488        1488        1488        1488        1488   
3              922         922         922         922         922   
4             1195        1195        1195        1195        1195   
...            ...         ...         ...         ...         ...   
159203        1490        1489        1489        1489        1490   
159204         938         938         936         937         938   
159205        1490        1489        1489        1489        1490   
159206  1111111111  1111111111  1111111111  1111111111  1111111111   
159207  1111111110  1111111110  1111111110  1111111110  1111111110   

               5           6           7           8           9    ...  \
0       4280755967  4280755967  4280755967  4280755967  4280755967  ...   
1                0           0           0           0           0  ...   
2             1488        1488        1488        1488        1488  ...   
3              922         922         922         922         922  ...   
4             1195        1195        1195        1195        1195  ...   
...            ...         ...         ...         ...         ...  ...   
159203        1489        1489        1489        1489        1489  ...   
159204         937         937         937         936         938  ...   
159205        1489        1490        1489        1490        1490  ...   
159206  1111111111  1111111111  1111111111  1111111111  1111111111  ...   
159207  1111111110  1111111110  1111111110  1111111110  1111111110  ...   

               990         991         992         993         994  \
0       4280690431  4280690431  4280690431  4280690431  4280690431   
1                0           0           0           0           0   
2             1503        1503        1503        1503        1503   
3              927         927         927         927         927   
4             1201        1201        1201        1201        1201   
...            ...         ...         ...         ...         ...   
159203        1503        1503        1504        1503        1502   
159204         939         940         940         939         940   
159205        1503        1503        1502        1503        1503   
159206  1111111111  1111111111  1111111111  1111111111  1111111111   
159207  1111111110  1111111110  1111111110  1111111110  1111111110   

               995         996         997         998         999  
0       4280690431  4280690431  4280690431  4280690431  4280690431  
1                0           0           0           0           0  
2             1503        1503        1503        1503        1503  
3              927         927         927         927         927  
4             1201        1201        1201        1201        1201  
...            ...         ...         ...         ...         ...  
159203        1503        1503        1503        1503        1503  
159204         941         940         940         938         939  
159205        1503        1503        1503        1503        1503  
159206  1111111111  1111111111  1111111111  1111111111  1111111111  
159207  1111111110  1111111110  1111111110  1111111110  1111111110  

[159208 rows x 1000 columns]

In [ ]:
all_columns2 = all_columns[6:159206]

In [ ]:
all_columns2

0     1     2     3     4     5     6     7     8     9    ...   990  \
6        937   937   938   938   938   937   937   937   937   937  ...   940   
7       1490  1489  1489  1489  1489  1489  1490  1490  1489  1491  ...  1503   
8        937   938   937   937   936   937   937   937   937   938  ...   940   
9       1490  1489  1490  1491  1490  1489  1489  1489  1490  1490  ...  1502   
10       937   937   937   937   938   939   936   937   936   938  ...   940   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
159201  1490  1489  1490  1490  1489  1490  1489  1490  1490  1491  ...  1503   
159202   938   937   937   936   938   937   936   937   937   937  ...   940   
159203  1490  1489  1489  1489  1490  1489  1489  1489  1489  1489  ...  1503   
159204   938   938   936   937   938   937   937   937   936   938  ...   939   
159205  1490  1489  1489  1489  1490  1489  1490  1489  1490  1490  ...  1503   

         991   992   993   994   995   996   997   998   999  
6        941   938   940   941   938   939   940   941   939  
7       1503  1503  1503  1502  1503  1503  1503  1503  1503  
8        941   939   940   939   940   941   938   939   939  
9       1504  1503  1503  1503  1503  1503  1504  1503  1502  
10       939   940   938   940   939   939   939   940   940  
...      ...   ...   ...   ...   ...   ...   ...   ...   ...  
159201  1503  1502  1503  1503  1503  1502  1503  1502  1502  
159202   940   940   940   939   940   940   940   940   939  
159203  1503  1504  1503  1502  1503  1503  1503  1503  1503  
159204   940   940   939   940   941   940   940   938   939  
159205  1503  1502  1503  1503  1503  1503  1503  1503  1503  

[159200 rows x 1000 columns]

In [ ]:
temp = []
for i in range(len(all_columns2)):
  if ( i % 2 == 0):
    temp = np.append(temp, all_columns2.iloc[i], axis = 0)

temp = np.reshape(temp, (79600,1000))
temp = np.transpose(temp)
print(temp)

[[937. 937. 937. ... 938. 938. 938.]
 [937. 938. 937. ... 937. 937. 938.]
 [938. 937. 937. ... 938. 937. 936.]
 ...
 [940. 938. 939. ... 940. 940. 940.]
 [941. 939. 940. ... 938. 940. 938.]
 [939. 939. 940. ... 939. 939. 939.]]


In [ ]:
volt = []
for i in range(len(all_columns2)):
  if ( i % 2 == 1):
    volt = np.append(volt, all_columns2.iloc[i], axis = 0)

volt = np.reshape(volt, (79600,1000))
volt = np.transpose(volt)
print(volt)

[[1490. 1490. 1490. ... 1490. 1490. 1490.]
 [1489. 1489. 1489. ... 1489. 1489. 1489.]
 [1489. 1490. 1490. ... 1490. 1489. 1489.]
 ...
 [1503. 1504. 1503. ... 1503. 1503. 1503.]
 [1503. 1503. 1503. ... 1502. 1503. 1503.]
 [1503. 1502. 1502. ... 1502. 1503. 1503.]]


In [ ]:
id = []
for i in range(10):
  for j in range(100):
    id.append(i+1)
id = np.reshape(id,(1000,1))
id

array([[ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],

In [ ]:
alg = []
for i in range(len(temp)):
  alg.append(2)
alg = np.reshape(alg,(1000,1))
alg

array([[2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
    

In [ ]:
time = []
for i in range(len(temp)):
  time.append(i+1)
time = np.reshape(time,(1000,1))
time

array([[   1],
       [   2],
       [   3],
       [   4],
       [   5],
       [   6],
       [   7],
       [   8],
       [   9],
       [  10],
       [  11],
       [  12],
       [  13],
       [  14],
       [  15],
       [  16],
       [  17],
       [  18],
       [  19],
       [  20],
       [  21],
       [  22],
       [  23],
       [  24],
       [  25],
       [  26],
       [  27],
       [  28],
       [  29],
       [  30],
       [  31],
       [  32],
       [  33],
       [  34],
       [  35],
       [  36],
       [  37],
       [  38],
       [  39],
       [  40],
       [  41],
       [  42],
       [  43],
       [  44],
       [  45],
       [  46],
       [  47],
       [  48],
       [  49],
       [  50],
       [  51],
       [  52],
       [  53],
       [  54],
       [  55],
       [  56],
       [  57],
       [  58],
       [  59],
       [  60],
       [  61],
       [  62],
       [  63],
       [  64],
       [  65],
       [  66],
       [  

In [ ]:
temp_id = np.append(id, alg, axis = 1)
temp_id = np.append(temp_id, time, axis = 1)
temp_id = np.append(temp_id, temp, axis = 1)
temp_id = pd.DataFrame(temp_id)
temp_id=temp_id.astype(int)
temp_id.rename(columns={temp_id.columns[0]:'id'}, inplace=True)
temp_id.rename(columns={temp_id.columns[1]:'alg'}, inplace=True)
temp_id.rename(columns={temp_id.columns[2]:'time'}, inplace=True)
temp_id

id  alg  time    3    4    5    6    7    8    9  ...  79593  79594  \
0     1    2     1  937  937  937  937  937  938  936  ...    936    937   
1     1    2     2  937  938  937  937  937  938  938  ...    937    937   
2     1    2     3  938  937  937  937  937  938  937  ...    938    936   
3     1    2     4  938  937  937  937  937  937  937  ...    938    937   
4     1    2     5  938  936  938  938  938  938  936  ...    938    937   
..   ..  ...   ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
995  10    2   996  938  940  939  939  939  939  940  ...    939    939   
996  10    2   997  939  941  939  938  939  939  941  ...    940    940   
997  10    2   998  940  938  939  939  940  939  938  ...    940    939   
998  10    2   999  941  939  940  939  940  939  939  ...    939    939   
999  10    2  1000  939  939  940  939  938  940  939  ...    940    939   

     79595  79596  79597  79598  79599  79600  79601  79602  
0      936    937    937    936    938    938    938    938  
1      937    937    936    937    937    937    937    938  
2      937    938    937    937    937    938    937    936  
3      936    936    937    936    936    938    936    937  
4      939    936    938    937    936    937    938    938  
..     ...    ...    ...    ...    ...    ...    ...    ...  
995    939    939    939    941    939    940    940    941  
996    940    940    939    938    938    939    940    940  
997    940    940    939    940    940    940    940    940  
998    940    940    939    939    940    938    940    938  
999    940    939    939    939    940    939    939    939  

[1000 rows x 79603 columns]

In [ ]:
volt_id = np.append(id, alg, axis = 1)
volt_id = np.append (volt_id, time, axis = 1)
volt_id = np.append (volt_id, volt, axis = 1)
volt_id = pd.DataFrame(volt_id)
volt_id=volt_id.astype(int)
volt_id.rename(columns={volt_id.columns[0]:'id'}, inplace=True)
volt_id.rename(columns={volt_id.columns[1]:'alg'}, inplace=True)
volt_id.rename(columns={volt_id.columns[2]:'time'}, inplace=True)
volt_id

id  alg  time     3     4     5     6     7     8     9  ...  79593  \
0     1    2     1  1490  1490  1490  1490  1490  1490  1490  ...   1490   
1     1    2     2  1489  1489  1489  1490  1489  1490  1490  ...   1490   
2     1    2     3  1489  1490  1490  1490  1489  1490  1489  ...   1490   
3     1    2     4  1489  1491  1489  1489  1489  1489  1490  ...   1489   
4     1    2     5  1489  1490  1490  1489  1490  1490  1490  ...   1490   
..   ..  ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
995  10    2   996  1503  1503  1502  1502  1503  1503  1502  ...   1503   
996  10    2   997  1503  1503  1503  1502  1503  1503  1503  ...   1502   
997  10    2   998  1503  1504  1503  1504  1503  1503  1503  ...   1503   
998  10    2   999  1503  1503  1503  1503  1503  1503  1503  ...   1502   
999  10    2  1000  1503  1502  1502  1502  1503  1503  1502  ...   1503   

     79594  79595  79596  79597  79598  79599  79600  79601  79602  
0     1489   1490   1491   1490   1490   1491   1490   1490   1490  
1     1490   1490   1490   1490   1489   1490   1489   1489   1489  
2     1489   1490   1490   1489   1489   1491   1490   1489   1489  
3     1490   1490   1490   1489   1489   1489   1490   1489   1489  
4     1490   1490   1489   1489   1489   1490   1489   1490   1490  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
995   1502   1503   1504   1503   1503   1504   1503   1503   1503  
996   1503   1504   1503   1503   1503   1503   1502   1503   1503  
997   1502   1502   1502   1503   1503   1503   1503   1503   1503  
998   1504   1503   1502   1503   1503   1504   1502   1503   1503  
999   1503   1502   1503   1503   1502   1503   1502   1503   1503  

[1000 rows x 79603 columns]

In [ ]:
temp_id.to_csv('temp_alg2.csv')

In [ ]:
volt_id.to_csv('volt_alg2.csv')